manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
     - name: PiXeL16                         #new entry
      url-base: https://github.com/PiXeL16 #new entry
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-landscape-slideshow          #new entry
      remote: PiXeL16                     #new entry
      revision: main                      #new entry
  self:
    path: config
